import '../../assets/scss/reset.scss'
import '../../assets/scss/form/checkbox.css'
import '../../assets/scss/public.scss'
import '../../assets/scss/payForOrder.scss'
import '../../assets/js/resetRem'
import './payForOrderOperation.js'
